name: Telegram Notifications

on:
  issues:
    types: [opened, edited, closed]
  pull_request:
    types: [opened, edited, closed, merged]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification
        run: |
          TOKEN="${{ secrets.TELEGRAM_TOKEN }}"
          CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}"
          MESSAGE="New event in GitHub repo: ${{ github.event_name }}"

          if [[ "${{ github.event_name }}" == "issues" ]]; then
            ISSUE_TITLE="${{ github.event.issue.title }}"
            ISSUE_URL="${{ github.event.issue.html_url }}"
            MESSAGE="New issue event: $ISSUE_TITLE\n$ISSUE_URL"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            PR_TITLE="${{ github.event.pull_request.title }}"
            PR_URL="${{ github.event.pull_request.html_url }}"
            MESSAGE="New pull request event: $PR_TITLE\n$PR_URL"
          fi

          curl -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
               -d chat_id="$CHAT_ID" \
               -d text="$MESSAGE"
